apiVersion: v1
kind: Service
metadata:
  name: cf-operator-webhook
spec:
{{- if .Values.provider.gke.externalIP }}
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.provider.gke.externalIP }}"
{{- end }}
  selector:
    name: cf-operator
  ports:
  - port: 2999
    targetPort: 2999
    name: cf-operator-webhook
