# Default values for cf-operator.
image:
  repository: cf-operator
  org: gcr.io/peripli
  tag: rhea
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

rbacEnable: true

serviceAccount:
  cfOperatorServiceAccount:
    create: true
    name:

provider: ""
